# GitHub Pages configuration for Miguel Gonzalez Resume
title: "Miguel Gonzalez - Resume"
description: "Professional resume of Miguel Gonzalez"

# Build settings
markdown: kramdown
highlighter: rouge

# GitHub Pages settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Collections and defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default